name: learn-github-actions
run-name : ${{ github.actor }} is learning github actions
on: [push]
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - run: chmod +x build
            - run: ./build
            - uses: actions/upload-artifact@v4
              with:
                name: hello
                path: hello