name: learn-github-actions
run-name : ${{ github.actor }} is learning github actions
on: [push]
jobs:
    job1:
        runs-on: [linux, x64]
        steps:
            - run: echo Linux-x64
            - run: ./build